ESPEAK_NG_VERSION = 1.52.0
ESPEAK_NG_SOURCE = $(ESPEAK_NG_VERSION).tar.gz
ESPEAK_NG_SITE = https://github.com/espeak-ng/espeak-ng/archive/refs/tags
ESPEAK_NG_LICENSE = GPL-3.0+, Apache-2.0, BSD-2-Clause, Unicode-DFS-2016
ESPEAK_NG_LICENSE_FILES = COPYING COPYING.APACHE COPYING.BSD2 COPYING.UCD

ESPEAK_NG_DEPENDENCIES = host-espeak-ng
ESPEAK_NG_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DESPEAK_COMPAT=ON \
	-DESPEAK_NG_DATA_COMPILER="$(HOST_DIR)/bin/espeak-ng" \
	-DESPEAK_NG_DATA_COMPILER_LD_LIBRARY_PATH="$(HOST_DIR)/lib" \
	-DESPEAK_USE_BUNDLED_SONIC=OFF

ifeq ($(BR2_PACKAGE_PCAUDIOLIB),y)
ESPEAK_NG_DEPENDENCIES += pcaudiolib
ESPEAK_NG_CONF_OPTS += -DUSE_LIBPCAUDIO=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_LIBPCAUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_LIBSONIC),y)
ESPEAK_NG_DEPENDENCIES += libsonic
ESPEAK_NG_CONF_OPTS += -DUSE_LIBSONIC=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_LIBSONIC=OFF
endif

ifeq ($(BR2_PACKAGE_ESPEAK_NG_SPEECH_PLAYER),y)
ESPEAK_NG_CONF_OPTS += -DUSE_SPEECHPLAYER=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_SPEECHPLAYER=OFF
endif

ifeq ($(BR2_PACKAGE_ESPEAK_NG_KLATT),y)
ESPEAK_NG_CONF_OPTS += -DUSE_KLATT=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_KLATT=OFF
endif

ifeq ($(BR2_PACKAGE_ESPEAK_NG_ASYNC),y)
ESPEAK_NG_CONF_OPTS += -DUSE_ASYNC=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_ASYNC=OFF
endif

ifeq ($(BR2_PACKAGE_ESPEAK_NG_MBROLA),y)
ESPEAK_NG_CONF_OPTS += -DUSE_MBROLA=ON
else
ESPEAK_NG_CONF_OPTS += -DUSE_MBROLA=OFF
endif

HOST_ESPEAK_NG_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DESPEAK_COMPAT=OFF \
	-DESPEAK_USE_BUNDLED_SONIC=OFF \
	-DUSE_LIBPCAUDIO=OFF \
	-DUSE_LIBSONIC=OFF \
	-DUSE_SPEECHPLAYER=OFF

ifeq ($(BR2_PACKAGE_ESPEAK_NG_MBROLA),y)
HOST_ESPEAK_NG_CONF_OPTS += -DUSE_MBROLA=ON
else
HOST_ESPEAK_NG_CONF_OPTS += -DUSE_MBROLA=OFF
endif

$(eval $(cmake-package))
$(eval $(host-cmake-package))
