LIBSONIC_VERSION = fda30fba867c08c82dbbecbcc72120652e40d5cb
LIBSONIC_SITE = https://github.com/espeak-ng/sonic.git
LIBSONIC_SITE_METHOD = git
LIBSONIC_LICENSE = Apache-2.0
LIBSONIC_LICENSE_FILES = LICENSE
LIBSONIC_INSTALL_STAGING = YES

LIBSONIC_LIB_NAME = libsonic.so
LIBSONIC_LIB_TAG = .0.3.0

LIBSONIC_MAKE_OPTS = \
	UNAME=Linux \
	CC="$(TARGET_CC)" \
	AR="$(TARGET_AR)" \
	CPPFLAGS="$(TARGET_CPPFLAGS)" \
	CFLAGS="$(TARGET_CFLAGS) -fPIC -pthread -Wall -Wno-unused-function -ansi" \
	LDFLAGS="$(TARGET_LDFLAGS)"

define LIBSONIC_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) -C $(@D) \
		$(LIBSONIC_MAKE_OPTS) \
		$(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG)
endef

define LIBSONIC_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0644 $(@D)/sonic.h \
		$(STAGING_DIR)/usr/include/sonic.h
	$(INSTALL) -D -m 0755 $(@D)/$(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(STAGING_DIR)/usr/lib/$(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG)
	ln -sf $(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(STAGING_DIR)/usr/lib/$(LIBSONIC_LIB_NAME)
	ln -sf $(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(STAGING_DIR)/usr/lib/$(LIBSONIC_LIB_NAME).0
endef

define LIBSONIC_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/$(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(TARGET_DIR)/usr/lib/$(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG)
	ln -sf $(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(TARGET_DIR)/usr/lib/$(LIBSONIC_LIB_NAME)
	ln -sf $(LIBSONIC_LIB_NAME)$(LIBSONIC_LIB_TAG) \
		$(TARGET_DIR)/usr/lib/$(LIBSONIC_LIB_NAME).0
endef

$(eval $(generic-package))
